columns = [
  Column.new(id: 1, name: 'status', label: 'Status', order: 1, columnable_type: 'LineItem'),
  Column.new(id: 2, name: 'required_action', label: 'Required Action', order: 2, columnable_type: 'LineItem'),
  Column.new(id: 3, name: 'order_number_field', label: 'Order Number', order: 3, columnable_type: 'LineItem'),
  Column.new(id: 4, name: 'order_date', label: 'Order Date', order: 4, columnable_type: 'LineItem'),
  Column.new(id: 5, name: 'wc_status', label: 'WC Status', order: 5, columnable_type: 'LineItem'),
  Column.new(id: 6, name: 'comment', label: 'Item Comment', order: 6, columnable_type: 'LineItem'),
  Column.new(id: 7, name: 'first_name', label: 'First Name', order: 7, columnable_type: 'LineItem'),
  Column.new(id: 8, name: 'last_name', label: 'Last Name', order: 8, columnable_type: 'LineItem'),
  Column.new(id: 9, name: 'country', label: 'Country', order: 9, columnable_type: 'LineItem'),
  Column.new(id: 10, name: 'email', label: 'Email', order: 10, columnable_type: 'LineItem'),
  Column.new(id: 11, name: 'phone', label: 'Phone', order: 11, columnable_type: 'LineItem'),
  Column.new(id: 12, name: 'customer', label: 'Customer', order: 12, columnable_type: 'LineItem'),
  Column.new(id: 13, name: 'name', label: 'Name', order: 13, columnable_type: 'LineItem'),
  Column.new(id: 14, name: 'quantity', label: 'Quantity', order: 14, columnable_type: 'LineItem'),
  Column.new(id: 15, name: 'items_in_order', label: 'Items in Order', order: 15, columnable_type: 'LineItem'),
  Column.new(id: 16, name: 'currency', label: 'Currency', order: 16, columnable_type: 'LineItem'),
  Column.new(id: 17, name: 'list_price', label: 'List Price', order: 17, columnable_type: 'LineItem'),
  Column.new(id: 18, name: 'paid_price', label: 'Paid Price', order: 18, columnable_type: 'LineItem'),
  Column.new(id: 19, name: 'order_total', label: 'Order Total', order: 19, columnable_type: 'LineItem'),
  Column.new(id: 20, name: 'sales_person_field', label: 'Sales Person', order: 20, columnable_type: 'LineItem'),
  Column.new(id: 21, name: 'location_of_sale', label: 'Location of Sale', order: 21, columnable_type: 'LineItem'),
  Column.new(id: 22, name: 'category', label: 'Category', order: 22, columnable_type: 'LineItem'),
  Column.new(id: 23, name: 'measurement_status', label: 'Measurement Status', order: 23, columnable_type: 'LineItem'),
  Column.new(id: 24, name: 'fabric_code', label: 'Fabric Code', order: 24, columnable_type: 'LineItem'),
  Column.new(id: 25, name: 'manufacturer_fabric_code', label: 'Manufacturer Fabric Code', order: 25, columnable_type: 'LineItem'),
  Column.new(id: 26, name: 'fabric_type', label: 'Fabric Type', order: 26, columnable_type: 'LineItem'),
  Column.new(id: 27, name: 'fabric_status', label: 'Fabric Status', order: 27, columnable_type: 'LineItem'),
  Column.new(id: 28, name: 'fabric_ordered_date_field', label: 'Fabric Ordered Date', order: 28, columnable_type: 'LineItem'),
  Column.new(id: 29, name: 'manufacturer_order_status', label: 'Manufacturer Order Status', order: 29, columnable_type: 'LineItem'),
  Column.new(id: 30, name: 'manufacturer_order_number', label: 'Manufacturer Order Number', order: 30, columnable_type: 'LineItem'),
  Column.new(id: 31, name: 'inbound_tracking_number', label: 'Inbound Tracking Number', order: 31, columnable_type: 'LineItem'),
  Column.new(id: 32, name: 'inbound_shipped_date', label: 'Inbound Shipped Date', order: 32, columnable_type: 'LineItem'),
  Column.new(id: 33, name: 'inbound_shipment_received_date', label: 'Inbound Shipment Received Date', order: 33, columnable_type: 'LineItem'),
  Column.new(id: 34, name: 'further_order_items_in_progress?', label: 'Further Order Items In Progress?', order: 34, columnable_type: 'LineItem'),
  Column.new(id: 35, name: 'alteration_tailor', label: 'Alteration Tailor', order: 35, columnable_type: 'LineItem'),
  Column.new(id: 36, name: 'courier_company', label: 'Courier Company', order: 36, columnable_type: 'LineItem'),
  Column.new(id: 37, name: 'outbound_tracking_number', label: 'Outbound Tracking Number', order: 37, columnable_type: 'LineItem'),
  Column.new(id: 38, name: 'next_appointment', label: 'Next Appointment', order: 38, columnable_type: 'LineItem'),
  Column.new(id: 39, name: 'is_remake', label: 'Remake', order: 39, columnable_type: 'LineItem'),
  Column.new(id: 40, name: 'shipping_company', label: 'Shipping Company', order: 40, columnable_type: 'LineItem'),
  Column.new(id: 41, name: 'shipping_address_1', label: 'Shipping Address 1', order: 41, columnable_type: 'LineItem'),
  Column.new(id: 42, name: 'shipping_address_2', label: 'Shipping Address 2', order: 42, columnable_type: 'LineItem'),
  Column.new(id: 43, name: 'shipping_city', label: 'Shipping City', order: 43, columnable_type: 'LineItem'),
  Column.new(id: 44, name: 'shipping_state', label: 'Shipping State', order: 44, columnable_type: 'LineItem'),
  Column.new(id: 45, name: 'shipping_postcode', label: 'Shipping Postcode', order: 45, columnable_type: 'LineItem'),
  Column.new(id: 46, name: 'shipping_first_name', label: 'Shipping First Name', order: 46, columnable_type: 'LineItem'),
  Column.new(id: 47, name: 'shipping_last_name', label: 'Shipping Last Name', order: 47, columnable_type: 'LineItem'),
  Column.new(id: 48, name: 'shipping_country', label: 'Shipping Country', order: 48, columnable_type: 'LineItem'),
  Column.new(id: 49, name: 'requested_completion_date', label: 'Requested Completion Date', order: 49, columnable_type: 'LineItem'),
  Column.new(id: 250, name: 'refunded_amount', label: 'Refunded Amount', order: 50, columnable_type: 'LineItem'),
  Column.new(id: 251, name: 'canvas', label: 'Canvas', order: 51, columnable_type: 'LineItem'),
  Column.new(id: 300, name: 'suit_fitting', label: 'Suit Fitting', order: 52, columnable_type: 'LineItem'),
  Column.new(id: 301, name: 'shirt_fit', label: 'Shirt Fit', order: 53, columnable_type: 'LineItem'),
  Column.new(id: 2017, name: 'to_be_shipped_date', label: 'To Be Shipped Date', order: 54, columnable_type: 'LineItem'),
  Column.new(id: 2019, name: 'urgent_field', label: 'Urgent', order: 56, columnable_type: 'LineItem'),
  Column.new(id: 4019, name: 'sent_to_alteration_date_field', label: 'Date sent to alterations tailor', order: 57, columnable_type: 'LineItem'),
  Column.new(id: 8000, name: 'date_entered_state', label: 'Date Entered State', order: 58, columnable_type: 'LineItem'),
  Column.new(id: 8001, name: 'last_email_sent_date', label: 'Last Email Sent Date', order: 59, columnable_type: 'LineItem'),
  Column.new(id: 8002, name: 'delivery_appointment_date_field', label: 'Delivery Appointment Date', order: 60, columnable_type: 'LineItem'),
  Column.new(id: 8888, name: 'delivery_method_post_alteration', label: 'Delivery Method Post Alteration', order: 61, columnable_type: 'LineItem'),
  Column.new(id: 8889, name: 'estimated_delivery_date', label: 'Estimated Delivery Date', order: 62, columnable_type: 'LineItem'),
  Column.new(id: 10000, name: 'order_comment_field', label: 'Order Comment', order: 63, columnable_type: 'LineItem'),
  Column.new(id: 11000, name: 'deduction_sales_amount', label: 'Deduction Sales to deduct from', order: 64, columnable_type: 'LineItem'),
  Column.new(id: 11001, name: 'deduction_sales_person_field', label: 'Sales person to deduct from', order: 65, columnable_type: 'LineItem'),
  Column.new(id: 11002, name: 'deduction_sales_comment_field', label: 'Comment - Sales Deduction', order: 66, columnable_type: 'LineItem'),
  Column.new(id: 11003, name: 'deduction_ops_amount', label: 'Deduction Ops to deduct from', order: 67, columnable_type: 'LineItem'),
  Column.new(id: 11004, name: 'deduction_ops_person_field', label: 'Ops person to deduct from', order: 68, columnable_type: 'LineItem'),
  Column.new(id: 11005, name: 'deduction_ops_comment_field', label: 'Comment - Ops Deduction', order: 69, columnable_type: 'LineItem'),
  Column.new(id: 11100, name: 'non_altered_items_field', label: 'Non-altered Items', order: 70, columnable_type: 'LineItem'),
  Column.new(id: 11110, name: 'garment_fit', label: 'Garment Fit', order: 71, columnable_type: 'LineItem'),
  Column.new(id: 15000, name: 'occasion_date_field', label: 'Occasion Date', order: 72, columnable_type: 'LineItem'),
  Column.new(id: 18000, name: 'customer_note', label: 'Customer Note(Woocommerce)', order: 73, columnable_type: 'LineItem'),
  Column.new(id: 21000, name: 'reminder_emails', label: 'Reminder Emails: ON/OFF', order: 74, columnable_type: 'LineItem'),
  Column.new(id: 22100, name: 'coupons', label: 'Coupons', order: 75, columnable_type: 'LineItem'),
  Column.new(id: 23100, name: 'fabric_brand', label: 'Fabric Brand', order: 76, columnable_type: 'LineItem'),
  Column.new(id: 23500, name: 'self_measured', label: 'Self Measured', order: 77, columnable_type: 'LineItem'),
  Column.new(id: 25500, name: 'acquisition_channel', label: 'Acquisition Channel - Checkout', order: 78, columnable_type: 'LineItem'),
  Column.new(id: 26610, name: 'customer_acquisition_channel', label: 'Acquisition Channel', order: 113, columnable_type: 'LineItem'),
  Column.new(id: 25600, name: 'refund_reason', label: 'Refund Reason', order: 79, columnable_type: 'LineItem'),
  Column.new(id: 25602, name: 'vat_export_field', label: 'VAT Export', order: 80, columnable_type: 'LineItem'),
  Column.new(id: 25604, name: 'remake_category_field', label: 'Remake Category', order: 81, columnable_type: 'LineItem'),
  Column.new(id: 26000, name: 'customer_type', label: 'Customer Type', order: 111, columnable_type: 'LineItem', sorting_scope: 'customer_type'),
  Column.new(id: 27001, name: 'manufacturer', label: 'Manufacturer', order: 114, columnable_type: 'LineItem', sorting_scope: 'manufacturer'),
  Column.new(id: 27502, name: 'fabric_tracking_number', label: 'Fabric Tracking Number', order: 115, columnable_type: 'LineItem', sorting_scope: 'fabric_tracking_number'),
  Column.new(id: 28000, name: 'tags_field', label: 'Tags', order: 116, columnable_type: 'LineItem'),
  Column.new(id: 28001, name: 'alteration_costs', label: 'Alteration Costs', order: 116, columnable_type: 'LineItem'),
  Column.new(id: 28501, name: 'comment_for_tailor', label: 'Comment for tailor', order: 117, columnable_type: 'LineItem'),
  Column.new(id: 29501, name: 'ordered_fabric', label: 'Fabric ordered?', order: 122, columnable_type: 'LineItem'),
  Column.new(id: 34183, name: 'special_customizations_field', label: 'Special Customizations', order: 123, columnable_type: 'LineItem'),
  Column.new(id: 34230, name: 'maybe_days_in_state_field', label: 'Days in current state', order: 124, columnable_type: 'LineItem'),
  Column.new(id: 34525, name: 'remind_to_get_measured', label: 'Remind to get measured', order: 125, columnable_type: 'LineItem'),
  Column.new(id: 51, name: 'status', order: 51, label: 'STATUS', columnable_type: 'Accounting', sorting_scope: 'state'),
  Column.new(id: 52, name: 'required_action', order: 52, label: 'REQUIRED ACTION', columnable_type: 'Accounting', sorting_scope: 'state'),
  Column.new(id: 53, name: 'order_number', order: 53, label: 'ORDER NO.', columnable_type: 'Accounting', sorting_scope: 'order_number'),
  Column.new(id: 54, name: 'order_date', order: 54, label: 'ORDER DATE', columnable_type: 'Accounting', sorting_scope: 'order_paid_date'),
  Column.new(id: 55, name: 'wc_status', order: 55, label: 'WC STATUS', columnable_type: 'Accounting'),
  Column.new(id: 56, name: 'comment', order: 56, label: 'COMMENT', columnable_type: 'Accounting'),
  Column.new(id: 57, name: 'first_name', order: 7, label: 'FIRST NAME', columnable_type: 'Accounting'),
  Column.new(id: 58, name: 'last_name', order: 58, label: 'LAST NAME', columnable_type: 'Accounting', sorting_scope: 'order_billable_last_name'),
  Column.new(id: 59, name: 'billing_country', order: 59, label: 'COUNTRY (BILLING)', columnable_type: 'Accounting', sorting_scope: 'order_billable_country'),
  Column.new(id: 25004, name: 'shipping_country', order: 59, label: 'COUNTRY (SHIPPING)', columnable_type: 'Accounting', sorting_scope: 'order_shippable_country'),
  Column.new(id: 60, name: 'email', order: 60, label: 'EMAIL', columnable_type: 'Accounting'),
  Column.new(id: 61, name: 'phone', order: 61, label: 'PHONE', columnable_type: 'Accounting'),
  Column.new(id: 62, name: 'customer', order: 62, label: 'CUSTOMER ID', columnable_type: 'Accounting'),
  Column.new(id: 63, name: 'name', order: 63, label: 'ITEM NAME', columnable_type: 'Accounting', sorting_scope: 'name'),
  Column.new(id: 64, name: 'quantity', order: 64, label: 'QUANTITY', columnable_type: 'Accounting'),
  Column.new(id: 65, name: 'items_in_order', order: 65, label: 'ITEMS IN ORDER', columnable_type: 'Accounting'),
  Column.new(id: 66, name: 'currency', order: 66, label: 'Currency', columnable_type: 'Accounting'),
  Column.new(id: 67, name: 'item_subtotal', order: 67, label: 'Subtotal', columnable_type: 'Accounting'),
  Column.new(id: 68, name: 'item_total', order: 68, label: 'Total (gross)', columnable_type: 'Accounting'),
  Column.new(id: 69, name: 'discount', order: 69, label: 'Discount', columnable_type: 'Accounting'),
  Column.new(id: 70, name: 'sales_person_field', order: 70, label: 'SALES PERSON', columnable_type: 'Accounting', sorting_scope: 'sales_person_first_name'),
  Column.new(id: 71, name: 'location_of_sale', order: 71, label: 'LOCATION OF SALE', columnable_type: 'Accounting', sorting_scope: 'sales_location_name'),
  Column.new(id: 72, name: 'category', order: 72, label: 'Category', columnable_type: 'Accounting', sorting_scope: 'product_category'),
  Column.new(id: 73, name: 'canvas', order: 73, label: 'Canvas', columnable_type: 'Accounting'),
  Column.new(id: 74, name: 'fabric_code', order: 74, label: 'Fabric Code', columnable_type: 'Accounting'),
  Column.new(id: 75, name: 'manufacturer_fabric_code', order: 75, label: 'RC Fabric Code', columnable_type: 'Accounting'),
  Column.new(id: 76, name: 'refunded_amount', order: 76, label: 'Refunded amount', columnable_type: 'Accounting'),
  Column.new(id: 77, name: 'total_after_refund', order: 77, label: 'Total (gross) after refund', columnable_type: 'Accounting'),
  Column.new(id: 22001, name: 'total_after_refund_sgd', order: 77, label: 'Total (gross) after refund (SGD)', columnable_type: 'Accounting'),
  Column.new(id: 78, name: 'vat_rate', order: 78, label: 'VAT rate', columnable_type: 'Accounting'),
  Column.new(id: 79, name: 'total_net_vat', order: 79, label: 'Total (net VAT)', columnable_type: 'Accounting'),
  Column.new(id: 80, name: 'cmt_cost_usd', order: 80, label: 'CMT cost (USD)', columnable_type: 'Accounting'),
  Column.new(id: 81, name: 'fabric_consumption', order: 81, label: 'Fabric consumption (m)', columnable_type: 'Accounting'),
  Column.new(id: 82, name: 'fabric_cost', order: 82, label: 'Fabric cost / M (USD)', columnable_type: 'Accounting'),
  Column.new(id: 83, name: 'manufacturing_costs', order: 83, label: 'Manufacturing costs (USD)', columnable_type: 'Accounting'),
  Column.new(id: 84, name: 'estimated_inbound_shipping_costs', order: 84, label: 'Estimated Inbound shipping costs (USD)', columnable_type: 'Accounting'),
  Column.new(id: 85, name: 'estimated_duty', order: 85, label: 'Estimated Duty (USD)', columnable_type: 'Accounting'),
  Column.new(id: 86, name: 'estimated_cogs', order: 86, label: 'Estimated COGS (landed) - USD', columnable_type: 'Accounting'),
  Column.new(id: 87, name: 'real_manufacturing_costs', order: 87, label: 'Real Manufacturing Costs (Real, USD)', columnable_type: 'Accounting'),
  Column.new(id: 88, name: 'real_cogs_fabric_addition_per_meter', order: 88, label: 'Real COGS - Fabric Addition per meter (USD)', columnable_type: 'Accounting'),
  Column.new(id: 89, name: 'real_cogs_fabric_addition_total', order: 89, label: 'Real COGS - Fabric Addition total (USD)', columnable_type: 'Accounting'),
  Column.new(id: 90, name: 'real_cogs_fabric_cmt_and_fabric_addition', order: 90, label: 'Real COGS - CMT & Fabric Addition (USD)', columnable_type: 'Accounting'),
  Column.new(id: 91, name: 'real_inbound_shipping_costs', order: 91, label: 'Real Inbound shipping costs (USD)', columnable_type: 'Accounting'),
  Column.new(id: 92, name: 'real_duty_usd', order: 92, label: 'Real Duty (USD)', columnable_type: 'Accounting'),
  Column.new(id: 93, name: 'real_cogs_landed_usd', order: 93, label: 'Real COGS - Landed (USD)', columnable_type: 'Accounting'),
  Column.new(id: 94, name: 'fx_usd_local_currency', order: 94, label: 'FX USD/Local Currency', columnable_type: 'Accounting'),
  Column.new(id: 95, name: 'real_cogs_landed_local_currency', order: 95, label: 'Real COGS - Landed (local currency)', columnable_type: 'Accounting'),
  Column.new(id: 260, name: 'manufacturer_order_number', order: 94, label: 'Manufacturer Order Number', columnable_type: 'Accounting'),
  Column.new(id: 96, name: 'margin', order: 96, label: 'Margin', columnable_type: 'Accounting'),
  Column.new(id: 12000, name: 'deduction_sales_amount', label: 'Deduction Sales to deduct from', order: 97, columnable_type: 'Accounting'),
  Column.new(id: 12001, name: 'deduction_sales_person_field', label: 'Sales person to deduct from', order: 98, columnable_type: 'Accounting'),
  Column.new(id: 12002, name: 'deduction_sales_comment_field', label: 'Comment - Sales Deduction', order: 99, columnable_type: 'Accounting'),
  Column.new(id: 12003, name: 'deduction_ops_amount', label: 'Deduction Ops to deduct from', order: 100, columnable_type: 'Accounting'),
  Column.new(id: 12004, name: 'deduction_ops_person_field', label: 'Ops person to deduct from', order: 101, columnable_type: 'Accounting'),
  Column.new(id: 12005, name: 'deduction_ops_comment_field', label: 'Comment - Ops Deduction', order: 102, columnable_type: 'Accounting'),
  Column.new(id: 22000, name: 'alteration_costs', label: 'Alteration Costs', order: 103, columnable_type: 'Accounting'),
  Column.new(id: 25001, name: 'is_remake', label: 'Remake', order: 104, columnable_type: 'Accounting'),
  Column.new(id: 25002, name: 'courier_company', label: 'Courier Company', order: 105, columnable_type: 'Accounting'),
  Column.new(id: 25003, name: 'outbound_tracking_number', label: 'Outbound Tracking Number', order: 106, columnable_type: 'Accounting'),
  Column.new(id: 25005, name: 'coupons', label: 'Coupons', order: 107, columnable_type: 'Accounting'),
  Column.new(id: 25601, name: 'refund_reason', label: 'Refund Reason', order: 107, columnable_type: 'Accounting'),
  Column.new(id: 25603, name: 'vat_export_field', label: 'VAT Export', order: 108, columnable_type: 'Accounting'),
  Column.new(id: 26601, name: 'customer_type', label: 'Customer Type', order: 112, columnable_type: 'Accounting', sorting_scope: 'customer_type'),
  Column.new(id: 27501, name: 'manufacturer', label: 'Manufacturer', order: 116, columnable_type: 'Accounting', sorting_scope: 'manufacturer'),
  Column.new(id: 29001, name: 'comment_for_tailor', label: 'Comment for tailor', order: 118, columnable_type: 'Accounting'),
  Column.new(id: 30001, name: 'ordered_fabric', label: 'Fabric ordered?', order: 123, columnable_type: 'Accounting'),
  Column.new(id: 33100, name: 'fabric_tracking_number', label: 'Fabric Tracking Number', order: 124, columnable_type: 'Accounting', sorting_scope: 'fabric_tracking_number'),
  Column.new(id: 33101, name: 'tags_field', label: 'Tags', order: 125, columnable_type: 'Accounting'),
  Column.new(id: 33102, name: 'fabric_brand', label: 'Fabric Brand', order: 126, columnable_type: 'Accounting'),
  Column.new(id: 33103, name: 'remake_category_field', label: 'Remake Category', order: 127, columnable_type: 'Accounting'),
  Column.new(id: 33104, name: 'customer_acquisition_channel', label: 'Acquisition Channel', order: 128, columnable_type: 'Accounting'),
  Column.new(id: 33105, name: 'non_altered_items_field', label: 'Non-altered Items', order: 129, columnable_type: 'Accounting'),
  Column.new(id: 33106, name: 'garment_fit', label: 'Garment Fit', order: 130, columnable_type: 'Accounting'),
  Column.new(id: 33107, name: 'occasion_date_field', label: 'Occasion Date', order: 131, columnable_type: 'Accounting'),
  Column.new(id: 33108, name: 'customer_note', label: 'Customer Note(Woocommerce)', order: 132, columnable_type: 'Accounting'),
  Column.new(id: 34220, name: 'special_customizations_field', label: 'Special Customizations', order: 133, columnable_type: 'Accounting'),
  Column.new(id: 34231, name: 'maybe_days_in_state_field', label: 'Days in current state', order: 134, columnable_type: 'Accounting'),
  Column.new(id: 34526, name: 'remind_to_get_measured', label: 'Remind to get measured', order: 135, columnable_type: 'Accounting'),
  Column.new(id: 97, name: 'manufacturer_id', label: 'Manufacturer ID', order: 1, columnable_type: 'RemainingCogs', sorting_scope: 'manufacturer_id'),
  Column.new(id: 98, name: 'order_number', label: 'Order No.', order: 2, columnable_type: 'RemainingCogs', sorting_scope: 'order_number'),
  Column.new(id: 99, name: 'name', label: 'Name', order: 3,  columnable_type: 'RemainingCogs', sorting_scope: 'name'),
  Column.new(id: 100, name: 'country', label: 'Country', order: 4, columnable_type: 'RemainingCogs', sorting_scope: 'country'),
  Column.new(id: 101, name: 'product_rc', label: 'Product RC', order: 5, columnable_type: 'RemainingCogs', sorting_scope: 'product_rc'),
  Column.new(id: 102, name: 'construction', label: 'Construction', order: 6, columnable_type: 'RemainingCogs', sorting_scope: 'construction'),
  Column.new(id: 103, name: 'meters', label: 'Meters', order: 7, columnable_type: 'RemainingCogs', sorting_scope: 'meters'),
  Column.new(id: 104, name: 'fabric', label: 'Fabric', order: 8, columnable_type: 'RemainingCogs', sorting_scope: 'fabric'),
  Column.new(id: 105, name: 'product_group', label: 'Product Group', order: 9, columnable_type: 'RemainingCogs', sorting_scope: 'product_group'),
  Column.new(id: 106, name: 'cogs_rc_usd', label: 'COGS RC USD', order: 10, columnable_type: 'RemainingCogs', sorting_scope: 'cogs_rc_usd'),
  Column.new(id: 107, name: 'order_date', label: 'Order Date', order: 11, columnable_type: 'RemainingCogs', sorting_scope: 'order_date'),
  Column.new(id: 108, name: 'deal_date', label: 'Deal date', order: 12, columnable_type: 'RemainingCogs', sorting_scope: 'deal_date'),
  Column.new(id: 109, name: 'matching_order_item', label: 'Matching Order item', order: 13, columnable_type: 'RemainingCogs', sorting_scope: 'matching_order_item'),
  Column.new(id: 110, name: 'cost_bucket', label: 'Cost Bucket', order: 14, columnable_type: 'RemainingCogs', sorting_scope: 'cost_bucket')
]

Column.import columns, on_duplicate_key_update: [:id, :name, :order, :columnable_type, :sorting_scope, :label]
puts 'Imported columns!'
