User.create(id: 1, first_name: 'reto', last_name: 'peter', email: 'reto@editsuits.com', password: 'password', password_confirmation: 'password', role: 1)
User.create(id: 2, first_name: 'nazar', last_name: 'taran', email: 'n.taran@bvblogic.com', password: 'password', password_confirmation: 'password', role: 1)

puts 'Imported admin user'

categories = [
  Category.new(id: 1, name: 'Height', order: 2, visible: false),
  Category.new(id: 2, name: 'Shirt', order: 3, visible: true),
  Category.new(id: 3, name: 'Jacket', order: 4, visible: true),
  Category.new(id: 4, name: 'Pants', order: 5, visible: true),
  Category.new(id: 5, name: 'Waistcoat', order: 7, visible: true),
  Category.new(id: 6, name: 'Overcoat', order: 8, visible: true),
  Category.new(id: 7, name: 'Chinos', order: 6, visible: true),
  Category.new(id: 8, name: 'Body shape & postures', order: 1, visible: false) 
]

Category.import categories, on_duplicate_key_update: [:id, :name, :order, :visible]
puts 'Imported categories'

# param_names_type_digits = ['Neck', 'Chest', 'Waist (Narrowest Point)', 'Waist (Belly Button)', 'Hip', 'Shoulder', 'Shirt Sleeve Length', 'Wrist / Cuff - without watch', 
#                               'Wrist / Cuff - with watch',  'Biceps', 'Shirt Length (front) - Tuck-in', 'Jacket Sleeve Length', 'Wrist / Cuff',
#                               'Jacket Length (front)' 'Jacket Length (back)' 'Button position - 2 buttons',
#                               'Button position - 1 buttons', 'Pant Waist', 'Hip - Pants', 'Rise', 'Thigh', 'Knee', 'Calf',
#                               'Pant cuff', 'Pant length (outseam)', 'Pant length (inseam)', 'Waistcoat Chest', 'Waistcoat Waist',
#                               'Waistcoat Front Length (pointed)', 'Waistcoat Front Length (straight)', 
#                               'Waistcoat Back Length', 'Waistcoat 1st Button Position', 'Overcoat Sleeve length', 
#                               'Overcoat Front Length', 'Overcoat Back Length', 'Button Position', 'Height (inches)', 'Height (cm)', 
#                               'Shirt length (back) - Tuck-in', 'Shirt length (front) - Tuck-out', 'Shirt length (back) - Tuck-out']

# param_names_type_values = ['Body type', 'Front Shoulder', 'Shoulder slope - Left', 'Shoulder slope - Right', 'Square Back Neck?',
#                               'Prominent Chest?', 'Arched back', 'Sleeve pitch', 'Prominent Seat?', 'Lower waistband in front']

params = [
  Param.new(id: 1, title: 'Neck', alias: 'Neck', input_type: :digits),
  Param.new(id: 2, title: 'Chest', alias: 'Chest', input_type: :digits),
  Param.new(id: 3, title: 'Waist (Button Position)', alias: 'Waist (Button Position)', input_type: :digits),
  Param.new(id: 4, title: 'Waist (Belly Button)', alias: 'Waist (Belly Button)', input_type: :digits),
  Param.new(id: 5, title: 'Hip', alias: 'Hip', input_type: :digits),
  Param.new(id: 6, title: 'Shoulder', alias: 'Shoulder', input_type: :digits),
  Param.new(id: 7, title: 'Shirt Sleeve Length', alias: 'Shirt Sleeve Length', input_type: :digits),
  Param.new(id: 8, title: 'Wrist / Cuff - without watch', alias: 'Wrist / Cuff - without watch', input_type: :digits),
  Param.new(id: 9, title: 'Wrist / Cuff - with watch', alias: 'Wrist / Cuff - with watch', input_type: :digits),
  Param.new(id: 10, title: 'Biceps', alias: 'Biceps', input_type: :digits),
  Param.new(id: 11, title: 'Shirt Length (front) - Tuck-in', alias: 'Shirt Length (front) - Tuck-in', input_type: :digits),
  Param.new(id: 12, title: 'Jacket Sleeve Length', alias: 'Jacket Sleeve Length', input_type: :digits),
  Param.new(id: 13, title: 'Wrist / Cuff', alias: 'Wrist / Cuff', input_type: :digits),
  Param.new(id: 14, title: 'Jacket Length (front)', alias: 'Jacket Length (front)', input_type: :digits),
  Param.new(id: 15, title: 'Jacket Length (back)', alias: 'Jacket Length (back)', input_type: :digits),
  Param.new(id: 16, title: 'Button position - 1 buttons', alias: 'Button position - 1 buttons', input_type: :digits),
  Param.new(id: 17, title: 'Button position - 2 buttons', alias: 'Button position - 2 buttons', input_type: :digits),
  Param.new(id: 18, title: 'Pant Waist', alias: 'Pant Waist', input_type: :digits),
  Param.new(id: 19, title: 'Hip - Pants', alias: 'Hip - Pants', input_type: :digits),
  Param.new(id: 20, title: 'Rise', alias: 'Rise', input_type: :digits),
  Param.new(id: 21, title: 'Thigh', alias: 'Thigh', input_type: :digits),
  Param.new(id: 22, title: 'Knee', alias: 'Knee', input_type: :digits),
  Param.new(id: 23, title: 'Calf', alias: 'Calf', input_type: :digits),
  Param.new(id: 24, title: 'Pant cuff', alias: 'Pant cuff', input_type: :digits),
  Param.new(id: 25, title: 'Pant length (outseam)', alias: 'Pant length (outseam)', input_type: :digits),
  Param.new(id: 26, title: 'Pant length (inseam)', alias: 'Pant length (inseam)', input_type: :digits),
  Param.new(id: 27, title: 'Waistcoat Chest', alias: 'Waistcoat Chest', input_type: :digits),
  Param.new(id: 28, title: 'Waistcoat Waist', alias: 'Waistcoat Waist', input_type: :digits),
  Param.new(id: 29, title: 'Waistcoat Front Length (pointed)', alias: 'Waistcoat Front Length (pointed)', input_type: :digits),
  Param.new(id: 30, title: 'Waistcoat Front Length (straight)', alias: 'Waistcoat Front Length (straight)', input_type: :digits),
  Param.new(id: 31, title: 'Waistcoat Back Length', alias: 'Waistcoat Back Length', input_type: :digits),
  Param.new(id: 32, title: 'Waistcoat 1st Button Position', alias: 'Waistcoat 1st Button Position', input_type: :digits),
  Param.new(id: 33, title: 'Overcoat Sleeve length', alias: 'Overcoat Sleeve length', input_type: :digits),
  Param.new(id: 34, title: 'Overcoat Front Length', alias: 'Overcoat Front Length', input_type: :digits),
  Param.new(id: 35, title: 'Overcoat Back Length', alias: 'Overcoat Back Length', input_type: :digits),
  Param.new(id: 36, title: 'Button Position', alias: 'Button Position', input_type: :digits),
  Param.new(id: 37, title: 'Height (inches)', alias: 'Height (inches)', input_type: :digits),
  Param.new(id: 38, title: 'Height (cm)', alias: 'Height (cm)', input_type: :digits),
  Param.new(id: 39, title: 'Shirt length (back) - Tuck-in', alias: 'Shirt length (back) - Tuck-in', input_type: :digits),
  Param.new(id: 40, title: 'Shirt length (front) - Tuck-out', alias: 'Shirt length (front) - Tuck-out', input_type: :digits),
  Param.new(id: 41, title: 'Shirt length (back) - Tuck-out', alias: 'Shirt length (back) - Tuck-out', input_type: :digits),
  Param.new(id: 42, title: 'Body type', alias: 'Body type', input_type: :values),
  Param.new(id: 43, title: 'Front Shoulder', alias: 'Front Shoulder', input_type: :values),
  Param.new(id: 44, title: 'Shoulder slope - Left', alias: 'Shoulder slope - Left', input_type: :values),
  Param.new(id: 45, title: 'Shoulder slope - Right', alias: 'Shoulder slope - Right', input_type: :values),
  Param.new(id: 46, title: 'Square Back Neck?', alias: 'Square Back Neck?', input_type: :values),
  Param.new(id: 47, title: 'Prominent Chest?', alias: 'Prominent Chest?', input_type: :values),
  Param.new(id: 48, title: 'Arched back', alias: 'Arched back', input_type: :values),
  Param.new(id: 49, title: 'Sleeve pitch', alias: 'Sleeve pitch', input_type: :values),
  Param.new(id: 50, title: 'Prominent Seat?', alias: 'Prominent Seat?', input_type: :values),
  Param.new(id: 51, title: 'Lower waistband in front', alias: 'Lower waistband in front', input_type: :values),
  Param.new(id: 52, title: 'Waist', alias: 'Waist', input_type: :digits),
  Param.new(id: 53, title: 'Hip - Pants - No pleats', alias: 'Hip - Pants - No pleats', input_type: :digits),
  Param.new(id: 54, title: 'Hip - Pants - With pleats', alias: 'Hip - Pants - With pleats', input_type: :digits),
  Param.new(id: 55, title: 'Wrist / Cuff - Button cuff - without watch', alias: 'Wrist / Cuff - Button cuff - without watch', input_type: :digits),
  Param.new(id: 56, title: 'Wrist / Cuff - Button cuff - with watch', alias: 'Wrist / Cuff - Button cuff - with watch', input_type: :digits),
  Param.new(id: 57, title: 'Wrist / Cuff - French cuff - without watch', alias: 'Wrist / Cuff - French cuff - without watch', input_type: :digits),
  Param.new(id: 58, title: 'Wrist / Cuff - French cuff - with watch', alias: 'Wrist / Cuff - French cuff - with watch', input_type: :digits),
  Param.new(id: 59, title: 'Chino-Outseam', alias: 'Chino-Outseam', input_type: :digits),
  Param.new(id: 60, title: 'Chino-Inseam', alias: 'Chino-Inseam', input_type: :digits),
  Param.new(id: 61, title: 'Chino-Outseam (left leg)', alias: 'Chino-Outseam (left leg)', input_type: :digits),
  Param.new(id: 62, title: 'Chino-Outseam (right leg)', alias: 'Chino-Outseam (right leg)', input_type: :digits),
  Param.new(id: 63, title: 'Chino-Inseam (left leg)', alias: 'Chino-Inseam (left leg)', input_type: :digits),
  Param.new(id: 64, title: 'Chino-Inseam (right leg)', alias: 'Chino-Inseam (right leg)', input_type: :digits),
  Param.new(id: 65, title: 'Pant length (outseam left leg)', alias: 'Pant length (outseam left leg)', input_type: :digits),
  Param.new(id: 66, title: 'Pant length (outseam right leg)', alias: 'Pant length (outseam right leg)', input_type: :digits),
  Param.new(id: 67, title: 'Pant length (inseam left leg)', alias: 'Pant length (inseam left leg)', input_type: :digits),
  Param.new(id: 68, title: 'Pant length (inseam right leg)', alias: 'Pant length (inseam right leg)', input_type: :digits),
  Param.new(id: 69, title: 'Shirt Sleeve Length (left sleeve)', alias: 'Shirt Sleeve Length (left sleeve)', input_type: :digits),
  Param.new(id: 70, title: 'Shirt Sleeve Length (right sleeve)', alias: 'Shirt Sleeve Length (right sleeve)', input_type: :digits),
  Param.new(id: 71, title: 'Jacket Sleeve Length (left sleeve)', alias: 'Jacket Sleeve Length (left sleeve)', input_type: :digits),
  Param.new(id: 72, title: 'Jacket Sleeve Length (right sleeve)', alias: 'Jacket Sleeve Length (right sleeve)', input_type: :digits),
  Param.new(id: 73, title: 'Overcoat Sleeve length (left sleeve)', alias: 'Overcoat Sleeve length (left sleeve)', input_type: :digits),
  Param.new(id: 74, title: 'Overcoat Sleeve length (right sleeve)', alias: 'Overcoat Sleeve length (right sleeve)', input_type: :digits),
  Param.new(id: 75, title: 'Armhole', alias: 'Armhole', input_type: :values),
  Param.new(id: 76, title: 'Back Shape', alias: 'Back Shape', input_type: :values),
  Param.new(id: 77, title: 'Hem', alias: 'Hem', input_type: :values),
  Param.new(id: 78, title: 'Rise', alias: 'Rise Dropdown', input_type: :values)
]

Param.import params, on_duplicate_key_update: [:id, :title, :alias, :input_type]
puts 'Imported params'


# value_names = ['No', 'Yes', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'Average', 'Slim', 'Muscular', 'Average with belly', 'Full figure', 'Normal', 'Slight forward',
#   'Very forward', 'Slight backwards', 'Very backwards', 'Slightly prominent chest', 'Very prominent chest', 'Forward']
values = [
  Value.new(id: 1, title: 'No'),
  Value.new(id: 2, title: 'Yes'),
  Value.new(id: 3, title: 'A'),
  Value.new(id: 4, title: 'B'),
  Value.new(id: 5, title: 'C'),
  Value.new(id: 6, title: 'D'),
  Value.new(id: 7, title: 'E'),
  Value.new(id: 8, title: 'F'),
  Value.new(id: 9, title: 'G'),
  Value.new(id: 10, title: 'Average'),
  Value.new(id: 11, title: 'Slim'),
  Value.new(id: 12, title: 'Muscular'),
  Value.new(id: 13, title: 'Average with belly'),
  Value.new(id: 14, title: 'Full figure'),
  Value.new(id: 15, title: 'Normal'),
  Value.new(id: 16, title: 'Slight forward'),
  Value.new(id: 17, title: 'Very forward'),
  Value.new(id: 18, title: 'Slight backwards'),
  Value.new(id: 19, title: 'Very backwards'),
  Value.new(id: 20, title: 'Slightly prominent chest'),
  Value.new(id: 21, title: 'Very prominent chest'),
  Value.new(id: 22, title: 'Forward'),
  Value.new(id: 23, title: 'Regular'),
  Value.new(id: 24, title: 'High'),
  Value.new(id: 25, title: 'Slightly Concave Waist'),
  Value.new(id: 26, title: 'Very Concave Waist'),
  Value.new(id: 27, title: 'Slight Humpback'),
  Value.new(id: 31, title: 'Moderate Humpback'),
  Value.new(id: 28, title: 'Very Humpback'),
  Value.new(id: 29, title: 'Straight'),
  Value.new(id: 30, title: 'Slanted'),
  Value.new(id: 32, title: 'Low')
]

Value.import values, on_duplicate_key_update: [:id, :title]
puts 'Imported values'


# params_hash = {
#   #id 2
#   shirt: ['Neck', 'Chest', 'Waist (Narrowest Point)', 'Waist (Belly Button)', 'Hip', 'Shoulder', 'Shirt Sleeve Length', 
#           'Wrist / Cuff - Button cuff - without watch', 'Wrist / Cuff - Button cuff - with watch', 'Wrist / Cuff - French cuff - without watch',  
#           'Wrist / Cuff - French cuff - with watch',
#           'Biceps', 'Shirt Length (front) - Tuck-in', 'Shirt length (back) - Tuck-in', 'Shirt length (front) - Tuck-out', 
#           'Shirt length (back) - Tuck-out'],
#   # id 3
#   jacket: ['Neck', 'Chest', 'Waist (Narrowest Point)', 'Waist (Belly Button)', 'Hip', 'Shoulder', 'Jacket Sleeve Length', 'Wrist / Cuff', 'Biceps', 
#            'Jacket Length (front)', 'Jacket Length (back)', 'Button position - 2 buttons', 'Button position - 1 buttons'],
#   # id 4
#   pants: ['Pant Waist', 'Hip - Pants - No pleats', 'Hip - Pants - With pleats', 'Rise', 'Thigh', 'Knee', 'Calf', 'Pant cuff', 'Pant length (outseam)', 'Pant length (inseam)'],
#   # id 5
#   waistcoat: ['Waistcoat Chest', 'Waistcoat Waist', 'Waistcoat Front Length (pointed)', 'Waistcoat Front Length (straight)', 
#                 'Waistcoat Back Length', 'Waistcoat 1st Button Position'],
#   #id 6
#   overcoat: ['Neck', 'Chest', 'Waist', 'Hip', 'Shoulder', 'Overcoat Sleeve length', 'Biceps', 'Overcoat Front Length', 'Overcoat Back Length', 'Button Position'],
#   # id 7
#   chinos: ['Pant Waist', 'Hip - Pants - No pleats', 'Hip - Pants - With pleats', 'Rise', 'Thigh', 'Knee', 'Calf', 'Pant cuff', 'Pant length (outseam)', 'Pant length (inseam)'],
#   # id 8
#   body_postures: ['Front Shoulder', 'Shoulder slope - Left', 'Shoulder slope - Right', 'Square Back Neck?',
#           'Prominent Chest?', 'Prominent Seat?', 'Body type'],
#   #id 1
#   height: ['Height (inches)', 'Height (cm)']
# }

category_params = [
  CategoryParam.new(id: 1, category_id: 1, param: Param.find_by(title: 'Height (inches)'), order: 1),
  CategoryParam.new(id: 2, category_id: 1, param: Param.find_by(title: 'Height (cm)'), order: 2),
  CategoryParam.new(id: 3, category_id: 2, param: Param.find_by(title: 'Neck'), order: 3),
  CategoryParam.new(id: 4, category_id: 2, param: Param.find_by(title: 'Chest'), order: 4),
  CategoryParam.new(id: 5, category_id: 2, param: Param.find_by(title: 'Waist (Button Position)'), order: 5),
  CategoryParam.new(id: 6, category_id: 2, param: Param.find_by(title: 'Waist (Belly Button)'), order: 6),
  CategoryParam.new(id: 7, category_id: 2, param: Param.find_by(title: 'Hip'), order: 7),
  CategoryParam.new(id: 8, category_id: 2, param: Param.find_by(title: 'Shoulder'), order: 8),
  CategoryParam.new(id: 9, category_id: 2, param: Param.find_by(title: 'Shirt Sleeve Length'), order: 9, deleted_at: Date.today),
  CategoryParam.new(id: 78, category_id: 2, param: Param.find_by(title: 'Shirt Sleeve Length (left sleeve)'), order: 10),
  CategoryParam.new(id: 79, category_id: 2, param: Param.find_by(title: 'Shirt Sleeve Length (right sleeve)'), order: 11),
  CategoryParam.new(id: 10, category_id: 2, param: Param.find_by(title: 'Wrist / Cuff - Button cuff - without watch'), order: 12),
  CategoryParam.new(id: 11, category_id: 2, param: Param.find_by(title: 'Wrist / Cuff - Button cuff - with watch'), order: 13),
  CategoryParam.new(id: 12, category_id: 2, param: Param.find_by(title: 'Wrist / Cuff - French cuff - without watch'), order: 14),
  CategoryParam.new(id: 13, category_id: 2, param: Param.find_by(title: 'Wrist / Cuff - French cuff - with watch'), order: 15),
  CategoryParam.new(id: 14, category_id: 2, param: Param.find_by(title: 'Biceps'), order: 16),
  CategoryParam.new(id: 15, category_id: 2, param: Param.find_by(title: 'Shirt Length (front) - Tuck-in'), order: 17),
  CategoryParam.new(id: 16, category_id: 2, param: Param.find_by(title: 'Shirt length (back) - Tuck-in'), order: 18),
  CategoryParam.new(id: 17, category_id: 2, param: Param.find_by(title: 'Shirt length (front) - Tuck-out'), order: 19),
  CategoryParam.new(id: 18, category_id: 2, param: Param.find_by(title: 'Shirt length (back) - Tuck-out'), order: 20),
  CategoryParam.new(id: 19, category_id: 3, param: Param.find_by(title: 'Neck'), order: 21),
  CategoryParam.new(id: 20, category_id: 3, param: Param.find_by(title: 'Chest'), order: 22),
  CategoryParam.new(id: 21, category_id: 3, param: Param.find_by(title: 'Waist (Button Position)'), order: 23),
  CategoryParam.new(id: 22, category_id: 3, param: Param.find_by(title: 'Waist (Belly Button)'), order: 24),
  CategoryParam.new(id: 23, category_id: 3, param: Param.find_by(title: 'Hip'), order: 25),
  CategoryParam.new(id: 24, category_id: 3, param: Param.find_by(title: 'Shoulder'), order: 26),
  CategoryParam.new(id: 25, category_id: 3, param: Param.find_by(title: 'Jacket Sleeve Length'), order: 27, deleted_at: Date.today),
  CategoryParam.new(id: 82, category_id: 3, param: Param.find_by(title: 'Jacket Sleeve Length (left sleeve)'), order: 28),
  CategoryParam.new(id: 83, category_id: 3, param: Param.find_by(title: 'Jacket Sleeve Length (right sleeve)'), order: 29),
  CategoryParam.new(id: 26, category_id: 3, param: Param.find_by(title: 'Wrist / Cuff'), order: 30),
  CategoryParam.new(id: 27, category_id: 3, param: Param.find_by(title: 'Biceps'), order: 31),
  CategoryParam.new(id: 28, category_id: 3, param: Param.find_by(title: 'Jacket Length (front)'), order: 32),
  CategoryParam.new(id: 29, category_id: 3, param: Param.find_by(title: 'Jacket Length (back)'), order: 33),
  CategoryParam.new(id: 30, category_id: 3, param: Param.find_by(title: 'Button position - 2 buttons'), order: 34),
  CategoryParam.new(id: 31, category_id: 3, param: Param.find_by(title: 'Button position - 1 buttons'), order: 35),
  CategoryParam.new(id: 32, category_id: 4, param: Param.find_by(title: 'Pant Waist'), order: 36),
  CategoryParam.new(id: 33, category_id: 4, param: Param.find_by(title: 'Hip - Pants - No pleats'), order: 37),
  CategoryParam.new(id: 34, category_id: 4, param: Param.find_by(title: 'Hip - Pants - With pleats'), order: 38),
  CategoryParam.new(id: 35, category_id: 4, param: Param.find_by(title: 'Rise'), order: 39),
  CategoryParam.new(id: 36, category_id: 4, param: Param.find_by(title: 'Thigh'), order: 40),
  CategoryParam.new(id: 37, category_id: 4, param: Param.find_by(title: 'Knee'), order: 41),
  CategoryParam.new(id: 38, category_id: 4, param: Param.find_by(title: 'Calf'), order: 42),
  CategoryParam.new(id: 39, category_id: 4, param: Param.find_by(title: 'Pant cuff'), order: 43),
  CategoryParam.new(id: 40, category_id: 4, param: Param.find_by(title: 'Pant length (outseam)'), order: 44, deleted_at: Date.today),
  CategoryParam.new(id: 84, category_id: 4, param: Param.find_by(title: 'Pant length (outseam left leg)'), order: 45),
  CategoryParam.new(id: 85, category_id: 4, param: Param.find_by(title: 'Pant length (outseam right leg)'), order: 46),
  CategoryParam.new(id: 41, category_id: 4, param: Param.find_by(title: 'Pant length (inseam)'), order: 47, deleted_at: Date.today),
  CategoryParam.new(id: 86, category_id: 4, param: Param.find_by(title: 'Pant length (inseam left leg)'), order: 48, deleted_at: Date.today),
  CategoryParam.new(id: 87, category_id: 4, param: Param.find_by(title: 'Pant length (inseam right leg)'), order: 49, deleted_at: Date.today),
  CategoryParam.new(id: 80, category_id: 4, param: Param.find_by(title: 'Chino-Outseam'), order: 50, deleted_at: Date.today),
  CategoryParam.new(id: 88, category_id: 4, param: Param.find_by(title: 'Chino-Outseam (left leg)'), order: 51, deleted_at: Date.today),
  CategoryParam.new(id: 89, category_id: 4, param: Param.find_by(title: 'Chino-Outseam (right leg)'), order: 52, deleted_at: Date.today),
  CategoryParam.new(id: 81, category_id: 4, param: Param.find_by(title: 'Chino-Inseam'), order: 53, deleted_at: Date.today),
  CategoryParam.new(id: 90, category_id: 4, param: Param.find_by(title: 'Chino-Inseam (left leg)'), order: 54, deleted_at: Date.today),
  CategoryParam.new(id: 91, category_id: 4, param: Param.find_by(title: 'Chino-Inseam (right leg)'), order: 55, deleted_at: Date.today),
  CategoryParam.new(id: 58, category_id: 7, param: Param.find_by(title: 'Pant Waist'), order: 56),
  CategoryParam.new(id: 59, category_id: 7, param: Param.find_by(title: 'Hip - Pants - No pleats'), order: 57),
  CategoryParam.new(id: 60, category_id: 7, param: Param.find_by(title: 'Hip - Pants - With pleats'), order: 58),
  CategoryParam.new(id: 61, category_id: 7, param: Param.find_by(title: 'Rise'), order: 59),
  CategoryParam.new(id: 62, category_id: 7, param: Param.find_by(title: 'Thigh'), order: 60),
  CategoryParam.new(id: 63, category_id: 7, param: Param.find_by(title: 'Knee'), order: 61),
  CategoryParam.new(id: 64, category_id: 7, param: Param.find_by(title: 'Calf'), order: 62),
  CategoryParam.new(id: 65, category_id: 7, param: Param.find_by(title: 'Pant cuff'), order: 63),
  CategoryParam.new(id: 66, category_id: 7, param: Param.find_by(title: 'Pant length (outseam)'), order: 64, deleted_at: Date.today),
  CategoryParam.new(id: 94, category_id: 7, param: Param.find_by(title: 'Pant length (outseam left leg)'), order: 65),
  CategoryParam.new(id: 95, category_id: 7, param: Param.find_by(title: 'Pant length (outseam right leg)'), order: 66),
  CategoryParam.new(id: 67, category_id: 7, param: Param.find_by(title: 'Pant length (inseam)'), order: 67, deleted_at: Date.today),
  CategoryParam.new(id: 96, category_id: 7, param: Param.find_by(title: 'Pant length (inseam left leg)'), order: 68, deleted_at: Date.today),
  CategoryParam.new(id: 97, category_id: 7, param: Param.find_by(title: 'Pant length (inseam right leg)'), order: 69, deleted_at: Date.today),
  CategoryParam.new(id: 42, category_id: 5, param: Param.find_by(title: 'Waistcoat Chest'), order: 70),
  CategoryParam.new(id: 100, category_id: 5, param: Param.find_by(title: 'Waist (Button Position)'), order: 71),
  CategoryParam.new(id: 43, category_id: 5, param: Param.find_by(title: 'Waist (Belly Button)'), order: 72),
  CategoryParam.new(id: 44, category_id: 5, param: Param.find_by(title: 'Waistcoat Front Length (pointed)'), order: 73),
  CategoryParam.new(id: 45, category_id: 5, param: Param.find_by(title: 'Waistcoat Front Length (straight)'), order: 74),
  CategoryParam.new(id: 46, category_id: 5, param: Param.find_by(title: 'Waistcoat Back Length'), order: 75),
  CategoryParam.new(id: 47, category_id: 5, param: Param.find_by(title: 'Waistcoat 1st Button Position'), order: 76),
  CategoryParam.new(id: 48, category_id: 6, param: Param.find_by(title: 'Neck'), order: 77),
  CategoryParam.new(id: 49, category_id: 6, param: Param.find_by(title: 'Chest'), order: 78),
  CategoryParam.new(id: 50, category_id: 6, param: Param.find_by(title: 'Waist'), order: 79),
  CategoryParam.new(id: 51, category_id: 6, param: Param.find_by(title: 'Hip'), order: 80),
  CategoryParam.new(id: 52, category_id: 6, param: Param.find_by(title: 'Shoulder'), order: 81),
  CategoryParam.new(id: 53, category_id: 6, param: Param.find_by(title: 'Overcoat Sleeve length'), order: 82, deleted_at: Date.today),
  CategoryParam.new(id: 92, category_id: 6, param: Param.find_by(title: 'Overcoat Sleeve length (left sleeve)'), order: 83),
  CategoryParam.new(id: 93, category_id: 6, param: Param.find_by(title: 'Overcoat Sleeve length (right sleeve)'), order: 84),
  CategoryParam.new(id: 54, category_id: 6, param: Param.find_by(title: 'Biceps'), order: 85),
  CategoryParam.new(id: 55, category_id: 6, param: Param.find_by(title: 'Overcoat Front Length'), order: 86),
  CategoryParam.new(id: 56, category_id: 6, param: Param.find_by(title: 'Overcoat Back Length'), order: 87),
  CategoryParam.new(id: 57, category_id: 6, param: Param.find_by(title: 'Button Position'), order: 88),
  CategoryParam.new(id: 68, category_id: 8, param: Param.find_by(title: 'Body type'), order: 89),
  CategoryParam.new(id: 69, category_id: 8, param: Param.find_by(title: 'Front Shoulder'), order: 90),
  CategoryParam.new(id: 70, category_id: 8, param: Param.find_by(title: 'Shoulder slope - Left'), order: 91),
  CategoryParam.new(id: 71, category_id: 8, param: Param.find_by(title: 'Shoulder slope - Right'), order: 92),
  CategoryParam.new(id: 72, category_id: 8, param: Param.find_by(title: 'Square Back Neck?'), order: 93),
  CategoryParam.new(id: 73, category_id: 8, param: Param.find_by(title: 'Prominent Chest?'), order: 94),
  CategoryParam.new(id: 74, category_id: 8, param: Param.find_by(title: 'Arched Back'), order: 95, deleted_at: Date.today),
  CategoryParam.new(id: 75, category_id: 8, param: Param.find_by(title: 'Sleeve Pitch'), order: 96),
  CategoryParam.new(id: 76, category_id: 8, param: Param.find_by(title: 'Prominent Seat?'), order: 97),
  CategoryParam.new(id: 77, category_id: 8, param: Param.find_by(title: 'Lower waistband in front'), order: 98),
  CategoryParam.new(id: 98, category_id: 8, param: Param.find_by(title: 'Armhole'), order: 99),
  CategoryParam.new(id: 99, category_id: 8, param: Param.find_by(title: 'Back Shape'), order: 100),
  CategoryParam.new(id: 101, category_id: 8, param: Param.find_by(title: 'Hem'), order: 101),
  CategoryParam.new(id: 102, category_id: 8, param: Param.find_by(alias: 'Rise Dropdown'), order: 102)
]


CategoryParam.import category_params, on_duplicate_key_update: [:id, :category_id, :param_id, :order, :deleted_at]
puts 'Imported Category Params'

values_hash = {
  body_type: ['Average', 'Slim', 'Muscular', 'Average with belly', 'Full figure'],
  front_shoulder: ['Normal', 'Slight forward', 'Very forward', 'Slight backwards', 'Very backwards'],
  shoulder_slope_left: ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
  shoulder_slope_right: ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
  square_back_neck: ['No', 'Yes'],
  prominent_chest: ['No', 'Slightly prominent chest', 'Very prominent chest'],
  arched_back: ['No', 'Yes'],
  sleeve_pitch: ['Normal', 'Forward', 'Slight backwards', 'Very backwards'],
  prominent_seat: ['No', 'Yes'],
  lower_waistband_in_front: ['No', 'Yes']
}

category_param_values = [
  CategoryParamValue.new(id: 1, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Body type', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Average').id),
  CategoryParamValue.new(id: 2, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Body type', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Slim').id),
  CategoryParamValue.new(id: 3, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Body type', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Muscular').id),
  CategoryParamValue.new(id: 4, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Body type', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Average with belly').id),
  CategoryParamValue.new(id: 5, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Body type', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Full figure').id),
  CategoryParamValue.new(id: 6, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Front Shoulder', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Normal').id),
  CategoryParamValue.new(id: 7, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Front Shoulder', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Slight forward').id),
  CategoryParamValue.new(id: 8, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Front Shoulder', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Very forward').id),
  CategoryParamValue.new(id: 9, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Front Shoulder', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Slight backwards').id),
  CategoryParamValue.new(id: 10, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Front Shoulder', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Very backwards').id),
  CategoryParamValue.new(id: 11, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder slope - Left', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'A').id),
  CategoryParamValue.new(id: 12, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder slope - Left', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'B').id),
  CategoryParamValue.new(id: 13, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder slope - Left', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'C').id),
  CategoryParamValue.new(id: 14, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder slope - Left', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'D').id),
  CategoryParamValue.new(id: 15, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder slope - Left', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'E').id),
  CategoryParamValue.new(id: 16, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder slope - Left', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'F').id),
  CategoryParamValue.new(id: 17, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder slope - Left', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'G').id),
  CategoryParamValue.new(id: 18, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder slope - Right', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'A').id),
  CategoryParamValue.new(id: 19, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder slope - Right', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'B').id),
  CategoryParamValue.new(id: 20, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder slope - Right', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'C').id),
  CategoryParamValue.new(id: 21, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder slope - Right', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'D').id),
  CategoryParamValue.new(id: 22, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder slope - Right', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'E').id),
  CategoryParamValue.new(id: 23, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder slope - Right', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'F').id),
  CategoryParamValue.new(id: 24, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder slope - Right', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'G').id),
  CategoryParamValue.new(id: 25, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Square Back Neck?', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'No').id),
  CategoryParamValue.new(id: 26, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Square Back Neck?', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Yes').id),
  CategoryParamValue.new(id: 27, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Prominent Chest?', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'No').id),
  CategoryParamValue.new(id: 28, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Prominent Chest?', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Slightly prominent chest').id),
  CategoryParamValue.new(id: 29, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Prominent Chest?', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Very prominent chest').id),
  CategoryParamValue.new(id: 30, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Arched Back', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'No').id),
  CategoryParamValue.new(id: 31, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Arched Back', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Yes').id),
  CategoryParamValue.new(id: 32, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Sleeve Pitch', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Normal').id),
  CategoryParamValue.new(id: 33, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Sleeve Pitch', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Forward').id),
  CategoryParamValue.new(id: 34, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Sleeve Pitch', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Slight backwards').id),
  CategoryParamValue.new(id: 35, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Sleeve Pitch', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Very backwards').id),
  CategoryParamValue.new(id: 36, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Prominent Seat?', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'No').id),
  CategoryParamValue.new(id: 37, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Prominent Seat?', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Yes').id),
  CategoryParamValue.new(id: 38, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Lower waistband in front', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'No').id),
  CategoryParamValue.new(id: 39, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Lower waistband in front', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Yes').id),
  CategoryParamValue.new(id: 40, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Armhole', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Regular').id),
  CategoryParamValue.new(id: 41, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Armhole', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'High').id),
  CategoryParamValue.new(id: 42, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Back Shape', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Normal').id),
  CategoryParamValue.new(id: 43, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Back Shape', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Slightly Concave Waist').id),
  CategoryParamValue.new(id: 44, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Back Shape', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Very Concave Waist').id),
  CategoryParamValue.new(id: 45, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Back Shape', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Slight Humpback').id),
  CategoryParamValue.new(id: 46, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Back Shape', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Moderate Humpback').id),
  CategoryParamValue.new(id: 47, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Back Shape', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Very Humpback').id),
  CategoryParamValue.new(id: 48, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Hem', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Straight').id),
  CategoryParamValue.new(id: 49, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Hem', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Slanted').id),
  CategoryParamValue.new(id: 50, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Rise', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Low').id),
  CategoryParamValue.new(id: 51, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Rise', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'Regular').id),
  CategoryParamValue.new(id: 52, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Rise', 'categories.name' => 'Body shape & postures'), value_id: Value.find_by(title: 'High').id)
]


CategoryParamValue.import category_param_values, on_duplicate_key_update: [:id, :category_param_id, :value_id]
puts 'Imported Param Values'


height_id = CategoryParam.find_param(:height, :height).id
chest_id = CategoryParam.find_param(:jacket, :chest).id
thigh_id = CategoryParam.find_param(:pants, :thigh).id
chinos_thigh_id = CategoryParam.find_param(:chinos, :thigh).id

measurement_checks = [
  MeasurementCheck.new(id: 1, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shirt Sleeve Length', 'categories.name' => 'Shirt'), percentile_id: height_id),
  MeasurementCheck.new(id: 21, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shirt Sleeve Length (left sleeve)', 'categories.name' => 'Shirt'), percentile_id: height_id),
  MeasurementCheck.new(id: 22, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shirt Sleeve Length (right sleeve)', 'categories.name' => 'Shirt'), percentile_id: height_id),
  MeasurementCheck.new(id: 2, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shirt Length (front) - Tuck-in', 'categories.name' => 'Shirt'), percentile_id: height_id),
  MeasurementCheck.new(id: 3, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder', 'categories.name' => 'Jacket'), percentile_of: :chest, percentile_id: chest_id),
  MeasurementCheck.new(id: 4, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Jacket Sleeve Length', 'categories.name' => 'Jacket'), percentile_id: height_id),
  MeasurementCheck.new(id: 23, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Jacket Sleeve Length (left sleeve)', 'categories.name' => 'Jacket'), percentile_id: height_id),
  MeasurementCheck.new(id: 24, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Jacket Sleeve Length (right sleeve)', 'categories.name' => 'Jacket'), percentile_id: height_id),
  MeasurementCheck.new(id: 5, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Jacket Length (front)', 'categories.name' => 'Jacket'), percentile_id: height_id),
  MeasurementCheck.new(id: 6, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Jacket Length (back)', 'categories.name' => 'Jacket'), percentile_id: height_id),
  MeasurementCheck.new(id: 7, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Rise', 'categories.name' => 'Pants'), calculations_type: :abs_value, percentile_id: height_id),
  MeasurementCheck.new(id: 8, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Knee', 'categories.name' => 'Pants'), percentile_of: :thigh, percentile_id: thigh_id),
  MeasurementCheck.new(id: 9, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant cuff', 'categories.name' => 'Pants'), calculations_type: :abs_value, percentile_id: height_id),
  MeasurementCheck.new(id: 10, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (outseam)', 'categories.name' => 'Pants'), percentile_id: height_id),
  MeasurementCheck.new(id: 25, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (outseam left leg)', 'categories.name' => 'Pants'), percentile_id: height_id),
  MeasurementCheck.new(id: 26, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (outseam right leg)', 'categories.name' => 'Pants'), percentile_id: height_id),
  MeasurementCheck.new(id: 11, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Waistcoat Front Length (pointed)', 'categories.name' => 'Waistcoat'), percentile_id: height_id),
  MeasurementCheck.new(id: 12, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Waistcoat Front Length (straight)', 'categories.name' => 'Waistcoat'), percentile_id: height_id),
  MeasurementCheck.new(id: 13, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder', 'categories.name' => 'Overcoat'), percentile_of: :chest, percentile_id: chest_id),
  MeasurementCheck.new(id: 14, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Overcoat Sleeve length', 'categories.name' => 'Overcoat'), percentile_id: height_id),
  MeasurementCheck.new(id: 27, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Overcoat Sleeve length (left sleeve)', 'categories.name' => 'Overcoat'), percentile_id: height_id),
  MeasurementCheck.new(id: 28, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Overcoat Sleeve length (right sleeve)', 'categories.name' => 'Overcoat'), percentile_id: height_id),
  MeasurementCheck.new(id: 15, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Overcoat Front Length', 'categories.name' => 'Overcoat'), percentile_id: height_id),
  MeasurementCheck.new(id: 16, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Overcoat Back Length', 'categories.name' => 'Overcoat'), percentile_id: height_id),
  MeasurementCheck.new(id: 17, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Rise', 'categories.name' => 'Chinos'), calculations_type: :abs_value, percentile_id: height_id),
  MeasurementCheck.new(id: 18, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant cuff', 'categories.name' => 'Chinos'), calculations_type: :abs_value, percentile_id: height_id),
  MeasurementCheck.new(id: 19, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (outseam)', 'categories.name' => 'Chinos'), percentile_id: height_id),
  MeasurementCheck.new(id: 29, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (outseam left leg)', 'categories.name' => 'Chinos'), percentile_id: height_id),
  MeasurementCheck.new(id: 30, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (outseam right leg)', 'categories.name' => 'Chinos'), percentile_id: height_id),
  MeasurementCheck.new(id: 20, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Knee', 'categories.name' => 'Chinos'), percentile_of: :chinos_thigh, percentile_id: chinos_thigh_id)
]

MeasurementCheck.import measurement_checks, validate: false, on_duplicate_key_update: [:id, :category_param_id, :percentile_id, :percentile_of, :calculations_type]
puts 'Imported Measurement Checks'

allowances = [
  Allowance.new(id: 1, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Neck', 'categories.name' => 'Jacket'), self_slim: -0.25, self_regular: -0.25),
  Allowance.new(id: 2, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Chest', 'categories.name' => 'Jacket'), slim: 2.00, singapore_slim: 1.5, regular: 2.25, self_slim: 1.5, self_regular: 2),
  Allowance.new(id: 3, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Waist (Button Position)', 'categories.name' => 'Jacket')),
  Allowance.new(id: 4, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Waist (Belly Button)', 'categories.name' => 'Jacket'), slim: 2.00, singapore_slim: 1.5, regular: 2.25, self_slim: 1.5, self_regular: 2.25),
  Allowance.new(id: 5, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Hip', 'categories.name' => 'Jacket'), slim: 1.75, singapore_slim: 1.5, regular: 2, self_slim: 1.5, self_regular: 2),
  Allowance.new(id: 6, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder', 'categories.name' => 'Jacket')),
  Allowance.new(id: 7, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Jacket Sleeve Length', 'categories.name' => 'Jacket')),
  Allowance.new(id: 68, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Jacket Sleeve Length (left sleeve)', 'categories.name' => 'Jacket')),
  Allowance.new(id: 69, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Jacket Sleeve Length (right sleeve)', 'categories.name' => 'Jacket')),
  Allowance.new(id: 8, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Wrist / Cuff', 'categories.name' => 'Jacket'), slim: 4.25, singapore_slim: 4.25, regular: 4.25, self_slim: 4, self_regular: 4.25),
  Allowance.new(id: 9, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Biceps', 'categories.name' => 'Jacket'), slim: 2.40, singapore_slim: 2.25, regular: 2.5, self_slim: 2.4, self_regular: 2.5),
  Allowance.new(id: 10, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Jacket Length (front)', 'categories.name' => 'Jacket')),
  Allowance.new(id: 11, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Jacket Length (back)', 'categories.name' => 'Jacket'), self_slim: -0.75, self_regular: -0.75),
  Allowance.new(id: 12, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Button position - 2 buttons', 'categories.name' => 'Jacket'), slim: 0.57, singapore_slim: 0.57, regular: 0.57, self_slim: 0.57, self_regular: 0.57),
  Allowance.new(id: 13, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Button position - 1 buttons', 'categories.name' => 'Jacket'), slim: 0.59, singapore_slim: 0.59, regular: 0.59, self_slim: 0.59, self_regular: 0.59),
  Allowance.new(id: 14, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant Waist', 'categories.name' => 'Pants')),
  Allowance.new(id: 15, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Hip - Pants - No pleats', 'categories.name' => 'Pants'), slim: 1.75, singapore_slim: 1.75, regular: 2, self_slim: 1.75, self_regular: 2),
  Allowance.new(id: 16, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Rise', 'categories.name' => 'Pants')),
  Allowance.new(id: 17, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Thigh', 'categories.name' => 'Pants'), slim: 2.0, singapore_slim: 2, regular: 2.50, self_slim: 1.75, self_regular: 2.25),
  Allowance.new(id: 18, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Knee', 'categories.name' => 'Pants')),
  Allowance.new(id: 19, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Calf', 'categories.name' => 'Pants')),
  Allowance.new(id: 20, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant cuff', 'categories.name' => 'Pants'), self_slim: -1, self_regular: 0),
  Allowance.new(id: 21, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (outseam)', 'categories.name' => 'Pants')),
  Allowance.new(id: 70, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (outseam left leg)', 'categories.name' => 'Pants')),
  Allowance.new(id: 71, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (outseam right leg)', 'categories.name' => 'Pants')),
  Allowance.new(id: 22, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (inseam)', 'categories.name' => 'Pants')),
  Allowance.new(id: 72, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (inseam left leg)', 'categories.name' => 'Pants')),
  Allowance.new(id: 73, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (inseam right leg)', 'categories.name' => 'Pants')),
  Allowance.new(id: 23, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Waistcoat Chest', 'categories.name' => 'Waistcoat'), slim: 1.00, singapore_slim: 1.00, regular: 1.00, self_slim: 0.5, self_regular: 0.75),
  Allowance.new(id: 24, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Waist (Button Position)', 'categories.name' => 'Waistcoat'), slim: 1.75, singapore_slim: 1.75, regular: 1.75, self_slim: 1.25, self_regular: 1.5),
  Allowance.new(id: 25, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Waistcoat Front Length (pointed)', 'categories.name' => 'Waistcoat'), slim: 2.00, singapore_slim: 2.00, regular: 2.00, self_slim: -1.5, self_regular: -1.5),
  Allowance.new(id: 26, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Waistcoat Front Length (straight)', 'categories.name' => 'Waistcoat'), self_slim: -3, self_regular: -3),
  Allowance.new(id: 27, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Waistcoat Back Length', 'categories.name' => 'Waistcoat'), self_slim: -3.5, self_regular: -3.5),
  Allowance.new(id: 28, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Waistcoat 1st Button Position', 'categories.name' => 'Waistcoat')),
  Allowance.new(id: 86, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Waist (Belly Button)', 'categories.name' => 'Waistcoat'), slim: 2.00, singapore_slim: 1.5, regular: 2.25, self_slim: 1.25, self_regular: 1.5),
  Allowance.new(id: 29, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Neck', 'categories.name' => 'Shirt')),
  Allowance.new(id: 30, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Chest', 'categories.name' => 'Shirt'), slim: 3.00, singapore_slim: 3.00, regular: 4.00, classic: 4.50, self_slim: 3, self_regular: 4),
  Allowance.new(id: 31, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Waist (Button Position)', 'categories.name' => 'Shirt')),
  Allowance.new(id: 32, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Waist (Belly Button)', 'categories.name' => 'Shirt'), slim: 2.30, singapore_slim: 2.30, regular: 3.50, classic: 4.50, self_slim: 2.3, self_regular: 3.5),
  Allowance.new(id: 33, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Hip', 'categories.name' => 'Shirt'), slim: 1.00, singapore_slim: 1.00, regular: 1.00, classic: 2.00, self_slim: 1, self_regular: 1.5),
  Allowance.new(id: 34, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder', 'categories.name' => 'Shirt')),
  Allowance.new(id: 35, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shirt Sleeve Length', 'categories.name' => 'Shirt')),
  Allowance.new(id: 74, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shirt Sleeve Length (left sleeve)', 'categories.name' => 'Shirt'), self_slim: 0.75, self_regular: 0.75),
  Allowance.new(id: 75, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shirt Sleeve Length (right sleeve)', 'categories.name' => 'Shirt'), self_slim: 0.75, self_regular: 0.75),
  Allowance.new(id: 36, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Wrist / Cuff - Button cuff - without watch', 'categories.name' => 'Shirt'), slim: 2.00, singapore_slim: 2.00, regular: 2.00, classic: 2.00, self_slim: 2, self_regular: 2),
  Allowance.new(id: 37, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Wrist / Cuff - Button cuff - with watch', 'categories.name' => 'Shirt'), slim: 2.25, singapore_slim: 2.25, regular: 2.25, classic: 2.25, self_slim: 2.5, self_regular: 2.5),
  Allowance.new(id: 38, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Biceps', 'categories.name' => 'Shirt'), slim: 2.40, singapore_slim: 2.40, regular: 3.00, classic: 3.50, self_slim: 2.5, self_regular: 3),
  Allowance.new(id: 39, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shirt length (front) - Tuck-in', 'categories.name' => 'Shirt')),
  Allowance.new(id: 40, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shirt length (back) - Tuck-in', 'categories.name' => 'Shirt'), slim: 1.00, singapore_slim: 1.00, regular: 1.00, classic: 1.00, self_slim: 1, self_regular: 1),
  Allowance.new(id: 41, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shirt length (front) - Tuck-out', 'categories.name' => 'Shirt'), slim: -2.00, singapore_slim: -2.00, regular: -2.00, classic: -2.00, self_slim: -1.5, self_regular: -1.5),
  Allowance.new(id: 42, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shirt length (back) - Tuck-out', 'categories.name' => 'Shirt'), slim: -1.00, singapore_slim: -1.00, regular: -1.00, classic: -1.00, self_slim: -0.5, self_regular: -0.5),
  Allowance.new(id: 43, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Neck', 'categories.name' => 'Overcoat')),
  Allowance.new(id: 44, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Chest', 'categories.name' => 'Overcoat'), slim: 2.75, singapore_slim: 2.75, regular: 3.25),
  Allowance.new(id: 45, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Waist', 'categories.name' => 'Overcoat'), slim: 3.50, singapore_slim: 3.50, regular: 4.00),
  Allowance.new(id: 46, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Hip', 'categories.name' => 'Overcoat'), slim: 3.25, singapore_slim: 4.00, regular: 3.25),
  Allowance.new(id: 47, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Shoulder', 'categories.name' => 'Overcoat'), slim: 0.25, singapore_slim: 0.25, regular: 0.25),
  Allowance.new(id: 48, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Overcoat Sleeve length', 'categories.name' => 'Overcoat'), slim: 0.50, singapore_slim: 0.50, regular: 0.50),
  Allowance.new(id: 76, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Overcoat Sleeve length (left sleeve)', 'categories.name' => 'Overcoat'), slim: 0.50, singapore_slim: 0.50, regular: 0.50),
  Allowance.new(id: 77, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Overcoat Sleeve length (right sleeve)', 'categories.name' => 'Overcoat'), slim: 0.50, singapore_slim: 0.50, regular: 0.50),
  Allowance.new(id: 49, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Biceps', 'categories.name' => 'Overcoat'), slim: 3.50, singapore_slim: 3.50, regular: 4.00),
  Allowance.new(id: 50, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Overcoat Front Length', 'categories.name' => 'Overcoat')),
  Allowance.new(id: 51, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Overcoat Back length', 'categories.name' => 'Overcoat')),
  Allowance.new(id: 52, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Button Position', 'categories.name' => 'Overcoat')),
  Allowance.new(id: 53, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant Waist', 'categories.name' => 'Chinos'), self_slim: 0.25, self_regular: 0.25),
  Allowance.new(id: 54, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Hip - Pants - No pleats', 'categories.name' => 'Chinos'), slim: 1.75, singapore_slim: 1.75, regular: 2, self_slim: 1.75, self_regular: 2),
  Allowance.new(id: 55, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Rise', 'categories.name' => 'Chinos')),
  Allowance.new(id: 56, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Thigh', 'categories.name' => 'Chinos'), slim: 2.0, singapore_slim: 2, regular: 2.50, self_slim: 2, self_regular: 2.5),
  Allowance.new(id: 57, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Knee', 'categories.name' => 'Chinos')),
  Allowance.new(id: 58, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Calf', 'categories.name' => 'Chinos')),
  Allowance.new(id: 59, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant cuff', 'categories.name' => 'Chinos'), self_slim: -1, self_regular: 0),
  Allowance.new(id: 60, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (outseam)', 'categories.name' => 'Chinos')),
  Allowance.new(id: 82, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (outseam left leg)', 'categories.name' => 'Chinos'), self_slim: 1, self_regular: 1),
  Allowance.new(id: 83, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (outseam right leg)', 'categories.name' => 'Chinos'), self_slim: 1, self_regular: 1),
  Allowance.new(id: 61, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (inseam)', 'categories.name' => 'Chinos')),
  Allowance.new(id: 84, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (inseam left leg)', 'categories.name' => 'Chinos')),
  Allowance.new(id: 85, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Pant length (inseam right leg)', 'categories.name' => 'Chinos')),
  Allowance.new(id: 62, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Wrist / Cuff - French cuff - without watch', 'categories.name' => 'Shirt'), slim: 2.25, singapore_slim: 2.25, regular: 2.25, classic: 2.25, self_slim: 2.25, self_regular: 2.25),
  Allowance.new(id: 63, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Wrist / Cuff - French cuff - with watch', 'categories.name' => 'Shirt'), slim: 2.50, singapore_slim: 2.50, regular: 2.50, classic: 2.50, self_slim: 2.75, self_regular: 2.75),
  Allowance.new(id: 64, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Hip - Pants - With pleats', 'categories.name' => 'Pants'), slim: 2.25, singapore_slim: 2.25, regular: 2.50, self_slim: 2.25, self_regular: 2.5),
  Allowance.new(id: 65, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Hip - Pants - With pleats', 'categories.name' => 'Chinos'), slim: 2.25, singapore_slim: 2.25, regular: 2.50, self_slim: 2.25, self_regular: 2.5),
  Allowance.new(id: 66, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Chino-Inseam', 'categories.name' => 'Pants')),
  Allowance.new(id: 78, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Chino-Inseam (left leg)', 'categories.name' => 'Pants')),
  Allowance.new(id: 79, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Chino-Inseam (right leg)', 'categories.name' => 'Pants')),
  Allowance.new(id: 67, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Chino-Outseam', 'categories.name' => 'Pants'), slim: 1.25, singapore_slim: 1.25, regular: 1.25),
  Allowance.new(id: 80, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Chino-Outseam (left leg)', 'categories.name' => 'Pants'), slim: 1.25, singapore_slim: 1.25, regular: 1.25),
  Allowance.new(id: 81, category_param: CategoryParam.joins(:param, :category).find_by('params.title' => 'Chino-Outseam (right leg)', 'categories.name' => 'Pants'), slim: 1.25, singapore_slim: 1.25, regular: 1.25)
]

Allowance.import allowances, validate: false, on_duplicate_key_update: [:id, :category_param_id, :slim, :singapore_slim, :regular, :classic, :self_slim, :self_regular]
puts 'Imported Allowances'
